model_type: "CombinedLoss" # Options: GCN, Vn, SpectralGCN, Combined, CombinedLoss

GCN:
  in_channels: 32
  hidden_channels: 64
  out_channels: 10
  num_layers: 3
  dropout: 0.3
  lr: 0.0001
  batch_size: 32
  monitor_metric: "val_ap"
  patience: 10
  max_epochs: 100
  checkpoint_path: "checkpoints\gcn_model_best_epoch=99_val_ap=0.4144.ckpt"

Vn:
  in_channels: 32
  hidden_channels: 64
  out_channels: 10
  num_layers: 3
  dropout: 0.3
  lr: 0.0001
  batch_size: 32
  k: 4
  monitor_metric: "val_ap"
  patience: 10
  max_epochs: 100
  num_vn: 4
  checkpoint_path: "checkpoints\vn_model_best_epoch=55_val_ap=0.5427.ckpt"

SpectralGCN:
  in_channels: 32
  hidden_channels: 64
  out_channels: 10
  num_layers: 3
  dropout: 0.3
  lr: 0.0001
  batch_size: 32
  k: 4
  num_heads: 4
  monitor_metric: "val_ap"
  patience: 10
  max_epochs: 100
  num_vn: 0
  checkpoint_path: "checkpoints\spectral_gcn_model_best_epoch=22_val_ap=0.2612_k=4.ckpt"
  

Combined:
  in_channels: 32
  hidden_channels: 64
  out_channels: 10
  num_layers: 3
  dropout: 0.3
  lr: 0.0001
  batch_size: 32
  k: 4
  num_heads: 4
  monitor_metric: "val_ap"
  patience: 10
  max_epochs: 100
  num_vn: 4
  checkpoint_path: "checkpoints\combined_model_best_epoch=05_val_ap=0.3722.ckpt"

CombinedLoss:
  in_channels: 32
  hidden_channels: 64
  out_channels: 10
  num_layers: 3
  dropout: 0.3
  lr: 0.0001
  batch_size: 32
  k: 4
  num_heads: 4
  monitor_metric: "val_ap"
  patience: 10
  max_epochs: 100
  num_vn: 4
  checkpoint_path: "checkpoints\combined_loss_model_best_epoch=36_val_ap=0.3421.ckpt"