_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 77
                - 103
            "3":
                - 7
                - 55
                - 66
            "4": 3.12.2
            "5": 0.20.1
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
dropout:
    value: 0.3
hidden_channels:
    value: 64
in_channels:
    value: 9
k:
    value: 4
lr:
    value: 0.0001
num_classes:
    value: 10
num_layers:
    value: 3
num_virtual_nodes:
    value: 4
