_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 77
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 77
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.13
            "5": 0.19.11
            "6": 4.52.4
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
dropout:
    value: 0.3
hidden_channels:
    value: 64
in_channels:
    value: 9
k:
    value: 4
lr:
    value: 0.0001
num_classes:
    value: 10
num_layers:
    value: 3
num_virtual_nodes:
    value: 4
